-- FMB News Daily Brief subscriber capture.
-- Public visitors may subscribe, but subscriber records are never publicly readable.

create table if not exists public.fmb_news_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  status text not null default 'subscribed' check (status in ('subscribed','unsubscribed','bounced','complained')),
  consented_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  source text not null default 'fmb-news-web',
  landing_path text,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fmb_news_subscribers_email_normalized check (email = lower(trim(email)))
);

create unique index if not exists fmb_news_subscribers_email_unique
  on public.fmb_news_subscribers ((lower(email)));

alter table public.fmb_news_subscribers enable row level security;

revoke all on table public.fmb_news_subscribers from anon, authenticated;
grant insert on table public.fmb_news_subscribers to anon, authenticated;
grant usage, select on sequence public.fmb_news_subscribers_id_seq to anon, authenticated;

drop policy if exists "public can subscribe to fmb news" on public.fmb_news_subscribers;
create policy "public can subscribe to fmb news"
  on public.fmb_news_subscribers
  for insert
  to anon, authenticated
  with check (
    status = 'subscribed'
    and unsubscribed_at is null
    and length(email) between 3 and 320
    and email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'
  );

comment on table public.fmb_news_subscribers is
  'FMB News Daily Brief newsletter subscribers. Public clients may insert only; subscriber records are not publicly readable.';
